GET http://localhost:5000/users/
###

GET http://localhost:5000/users/999
###
POST http://localhost:5000/users/signup
Content-Type: application/json 

{
    "email":"bmj@qq.com",
    "password":"086086Ed",
    "name":"Baomeijia"
}
###
POST http://localhost:5000/users/login
Content-Type: application/json 

{
    "email":"q22w@qq.com",
    "password":"abcdaaa"
}

###
#login with email and password
POST http://localhost:5000/users/login
Content-Type: application/json 

{
    "email":"darrenyipzy@gmail.com",
    "password":"abcd1234"
}


###
# get all Products
GET http://localhost:5000/products


### 
# Create product
POST http://localhost:5000/products/create
Content-Type: application/json 

{
    "name":"cake",
    "price":22.89,
    "unit":"g",
    "volumn": 24,
    "inStock": 150,
    "unitWeight": 200,
    "codeInSystem":"12327654",
    "barcode":"11422184"
}