GET http://localhost:5000/users/
###

GET http://localhost:5000/users/999
###
POST http://localhost:5000/users/signup
Content-Type: application/json 

{
    "email":"qq2w@qq.com",
    "password":"abcdaaa",
    "name":"darren"
}
###
POST http://localhost:5000/users/login
Content-Type: application/json 

{
    "email":"q22w@qq.com",
    "password":"abcdaaa"
}